name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy E-Commerce Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'jetbrains' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml
